apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: practice3
  labels:
    app.kubernetes.io/part-of: practice3-idempotency
type: Opaque
stringData:
  # URL Redis (в проде — с паролем: redis://:password@redis:6379/0)
  REDIS_URL: "redis://redis:6379/0"
  REDIS_PASSWORD: ""
